### ISSUE TITLE
NetIQ Feedback 9-10-2015

### ISSUE THREAD

**Issue by weiaiwayne** [jeffhoye/netiq#11]
INTRODUCTION

-- Please highlight/embolden important words like "link" or "node."
-- Please replace the introduction paragraph with the following:

"You may have heard of the concept of "six degrees of separation." This is the idea that every person in the world is connected to every other person through a small number of relationships. "Six degrees" is based on the concept of networks. A network  is a system of interconnected people as represented by nodes and links. Networks of people and their relationships are everywhere, including on the Internet, in professional settings, and even in your own family! 

Knowing ins and outs of networks is an important skill. It can help you advance your career, make friends, and get to know your neighbors. We have created this test to measure your "NetIQ" —how good you are at seeing patterns in networks.

In the test, you will see a network. You will either get a written description of the network or a picture depicting what the network looks like. Your task is to use the materials to correctly answer all of the questions about the network. The quicker you give the right answers, the better!"

-- Please replace the node-link diagram and association matrix with ones for a network of five nodes. (having fewer nodes makes it easier for participants to grasp basic network concepts).

-- Please label a node and a link in the node-link diagram and association matrix.

-- Please assign names (instead of letters) to the nodes.

-- Increase the font size of paragraph to 12 pt. 

-- Please place figure titles on top of graphs, that is, the body of text starting with Node-link diagram-- and Association Matrix-- is above the node-link diagram and association matrix.

-- Please provide a visual representation of hops, same as what we will do with nodes and links.

-- Please add a new term in the Terminology section about cluster: A cluster is a group within a network where every person in the group is connected to every other person in the group.

-- Following the introduction of the new term, please provide a visual representation of the concept.

-- Please add a text reminding participants not to hit refresh page in their browser. The reminder should stay throughout the test.

TEST QUESTIONS

-- Participants should be shown either text description or visualization (diagram/matrix), not both. 
-- Add the following questions on the end of the survey for capturing demographic data:

What is your gender?
         Male
         Female
         Other 

What is your race (check all that apply)?
        White/Caucasian
        Black/African American
        Native American/Alaska Native/Hawaii Native
        Latino/Hispanic
        Asian
        Other

Is English your first language? 
        Yes/No

-- Increase the font size of paragraph to 12 pt. 

-- Please set a time limit of 10 minutes for each scenario.

-- Please replace the countdown on each page with a small, nondescript timer, with a text reminding 

-- Change the following question 

Q: How many distinct groups of 3 or more interconnected people are there?

To

Q: How many clusters of 3 or more interconnected people are there? (Note: A cluster is a group     within a network where every person in the group is connected to every other person in the group)

-- In the visualization of nonprofit network, change Timothy Nager to Dr. Timothy Nager. 

-- In the textual description of domestic terrorist network, change "youtube" to "YouTube".

-- In the textual description of nonprofit network, change "generally" to "generously". 

-- Each play should be limited to one scenario only. 

CONFIRMATION PAGE

-- Please show a participant’s NetIQ score. Something that reads: Congratulations, you got 14 questions right within xxxx minutes! 

-- If possible, add a share button on the confirmation page that lets participants share their NetIQ score on Facebook. 

FURTHER STEPS

On top of node-link diagram and association matrix, can we produce an adjacent matrix as the third visualization option? And test it against the other two options. If you can send me raw network files (edge-list or matrix), I can help with producing the graph.

**Comment by jeffhoye** [comment]
Most of these are complete.  Everything that isn't is its own issue.  Please take a look.  The facebook thing even works!
