### ISSUE TITLE
keep text/visualization display 

### ISSUE THREAD

**Issue by weiaiwayne** [jeffhoye/netiq#18]
Please keep textual description or visualization on top of each question. Participants need to refer to text/visualization for answering questions.

**Comment by jeffhoye** [comment]
No prob.  FYI, I've built in a cool way for you to manage these kinds
of factors into Volunteer Science.
http://volunteerscience.com/experiment/165/

See "Variables" (about 1/3 down)
display_during_questions -- true / false whether to show description
during questions.

I just now set it to true, so that works now.  There are plenty other
parameters you can set.

_Don't forget to press update_

-Jeff

**Comment by weiaiwayne** [comment]
The link doesn't seem working, Jeff. Can you check?

Wayne

On Fri, Sep 18, 2015 at 1:02 AM, Jeff Hoye notifications@github.com wrote:

> No prob. FYI, I've built in a cool way for you to manage these kinds
> of factors into Volunteer Science.
> http://volunteerscience.com/experiment/165/
> 
> See "Variables" (about 1/3 down)
> display_during_questions -- true / false whether to show description
> during questions.
> 
> I just now set it to true, so that works now. There are plenty other
> parameters you can set.
> 
> _Don't forget to press update_
> 
> -Jeff
> 
> On Thu, Sep 17, 2015 at 8:44 PM, Curiosity Bits
> notifications@github.com wrote:
> 
> > Please keep textual description or visualization on top of each question.
> > Participants need to refer to text/visualization for answering questions.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jeffhoye/netiq/issues/18#issuecomment-141345397.

## 

Weiai Wayne Xu, PhD
http://curiositybits.com/
curiositybits.com

_CuriosityBits Collective_ - blending social data analytics with
qualitative richness to enhance digital advocacy and community engagement.
Learn more at curiositybits.org

**Comment by jeffhoye** [comment]
Try logging in first.

**Comment by weiaiwayne** [comment]
It works. Great! Thanks!

On Fri, Sep 18, 2015 at 10:29 AM, Jeff Hoye notifications@github.com
wrote:

> Try logging in first.
> On Sep 18, 2015 9:01 AM, "Curiosity Bits" notifications@github.com
> wrote:
> 
> > The link doesn't seem working, Jeff. Can you check?
> > 
> > Wayne
> > 
> > On Fri, Sep 18, 2015 at 1:02 AM, Jeff Hoye notifications@github.com
> > wrote:
> > 
> > > No prob. FYI, I've built in a cool way for you to manage these kinds
> > > of factors into Volunteer Science.
> > > http://volunteerscience.com/experiment/165/
> > > 
> > > See "Variables" (about 1/3 down)
> > > display_during_questions -- true / false whether to show description
> > > during questions.
> > > 
> > > I just now set it to true, so that works now. There are plenty other
> > > parameters you can set.
> > > 
> > > _Don't forget to press update_
> > > 
> > > -Jeff
> > > 
> > > On Thu, Sep 17, 2015 at 8:44 PM, Curiosity Bits
> > > notifications@github.com wrote:
> > > 
> > > > Please keep textual description or visualization on top of each
> > > > question.
> > > > Participants need to refer to text/visualization for answering
> > > > questions.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/jeffhoye/netiq/issues/18#issuecomment-141345397.
> > 
> > ## 
> > 
> > Weiai Wayne Xu, PhD
> > http://curiositybits.com/
> > curiositybits.com
> > 
> > _CuriosityBits Collective_ - blending social data analytics with
> > qualitative richness to enhance digital advocacy and community
> > engagement.
> > Learn more at curiositybits.org
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jeffhoye/netiq/issues/18#issuecomment-141445313.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jeffhoye/netiq/issues/18#issuecomment-141469319.

## 

Weiai Wayne Xu, PhD
http://curiositybits.com/
curiositybits.com

_CuriosityBits Collective_ - blending social data analytics with
qualitative richness to enhance digital advocacy and community engagement.
Learn more at curiositybits.org
