### ISSUE TITLE
incompatible with Microsoft Edge Browser  

### ISSUE THREAD

**Issue by weiaiwayne** [jeffhoye/netiq#20]
If incompatible, pls advise recommended browsers (Chrome, Safari and Firefox) on the first page,

**Comment by jeffhoye** [comment]
What's wrong with edge?  I'd tried it before.

**Comment by weiaiwayne** [comment]
The questions and graph won't load in the grey area. Maybe it is
machine-specific? I don't have another Win 10 machine to test it out.

On Fri, Sep 18, 2015 at 4:03 PM, Jeff Hoye notifications@github.com wrote:

> What's wrong with edge? I'd tried it before.
> 
> On Fri, Sep 18, 2015 at 2:55 PM, Curiosity Bits notifications@github.com
> wrote:
> 
> > If incompatible, pls advise recommended browsers (Chrome, Safari and
> > Firefox) on the first page,
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jeffhoye/netiq/issues/20.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jeffhoye/netiq/issues/20#issuecomment-141552776.

## 

Weiai Wayne Xu, PhD
http://curiositybits.com/
curiositybits.com

_CuriosityBits Collective_ - blending social data analytics with
qualitative richness to enhance digital advocacy and community engagement.
Learn more at curiositybits.org

**Comment by jeffhoye** [comment]
If possible, attach a screen shot to the issue.

**Comment by weiaiwayne** [comment]
![2015-09-18 17_03_03-photos](https://cloud.githubusercontent.com/assets/6760157/9971070/37cba57c-5e27-11e5-936d-b2a23ca7f440.png)

**Comment by jeffhoye** [comment]
fixed
